name: qgl-heartbeat
on:
  push:
  repository_dispatch:
    types: [zhoutian, heartbeat]
  workflow_dispatch:
jobs:
  heartbeat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      HUB_PAT: ${{ secrets.LINE_PAT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: heartbeat
        run: python engine-tower/heartbeat_api.py
